---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu18
    box: bento/ubuntu-18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu18
verifier:
  name: testinfra
  lint:
    name: flake8
