---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos7
    box: bento/centos-7.5
    groups:
      - linux
provisioner:
  name: ansible
  inventory:
    host_vars:
      windows2016:
        ansible_connection: winrm
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_port: 55985
        ansible_winrm_scheme: http
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
