---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: centos6
    box: bento/centos-6.10
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: el6
verifier:
  name: testinfra
  lint:
    name: flake8
